// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBTmFLTdoYAvFdZ7GIIlD7yNjPTokX2Xo',
    appId: '1:240473939613:web:e1d483e6ba55a1bad9fe74',
    messagingSenderId: '240473939613',
    projectId: 'adminperpus-1c46e',
    authDomain: 'adminperpus-1c46e.firebaseapp.com',
    storageBucket: 'adminperpus-1c46e.firebasestorage.app',
    measurementId: 'G-LH5ZM1THY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1DvJo0zEJeDooI5_2VZvo26ofPv2F8to',
    appId: '1:240473939613:android:349e603df8a7fc10d9fe74',
    messagingSenderId: '240473939613',
    projectId: 'adminperpus-1c46e',
    storageBucket: 'adminperpus-1c46e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVSTm7Pq69OhJ5Ep5Pfo1ivlbX0cXoejU',
    appId: '1:240473939613:ios:5a2975771f539ad2d9fe74',
    messagingSenderId: '240473939613',
    projectId: 'adminperpus-1c46e',
    storageBucket: 'adminperpus-1c46e.firebasestorage.app',
    iosBundleId: 'com.example.adminperpus',
  );
}
